let btn = document.querySelector("#new-quote");
let quote = document.querySelector(".quote");
let person = document.querySelector(".person");

//thos are the quotes that will be deplayed //
const quotes = [
  {
    quote:
      "“I don't go by the rule book... I lead from the heart, not the head.“",
    person: "Diana",
  },
  {
    quote:
      "“Success is not final, failure is not fatal: It is the courage to continue that counts.“",
    person: "Winston Churchill",
  },
  {
    quote: "“The way to get started is to quit talking and begin doing.”",
    person: " Walt Disney",
  },
  {
    quote: "“life goes on .”",
    person: "banghtan",
  },
  {
    quote:
      "“If life were predictable it would cease to be life, and be without flavor.” ",
    person: "Eleanor Roosevelt",
  },
  {
    quote: "“i dont know what im doing in my life either .” ",
    person: "me",
  },

  {
    quote:
      "”Everything negative – pressure, challenges – is all an opportunity for me to rise.”",
    person: "Kobe Bryant",
  },
  {
    quote:
      "“Almost everything will work again if you unplug it for a few minutes, including you.”",
    person: "Anne Lamott",
  },
  {
    quote:
      "“Don't let anyone tell you what you can't do. Follow your dreams and persist.“",
    person: " Barack Obama",
  },
];
//this function is used to genertae quotes the number of quotes will be took from the quotes/length
//Math.random() * quotes.length: This multiplies the random decimal number generated by Math.random() with the length of the quotes array. The result is a random number between 0  and the length of the quotes array (exclusive). This expression scales the random number to the size of the array.//
btn.addEventListener("click", function () {
  let random = Math.floor(Math.random() * quotes.length);
  quote.innerText = quotes[random].quote;
  person.innerText = quotes[random].person;
});
// this function is used to save favs quotes once u click on heart that quote will be saved as a const
let favoriteHeart = document.getElementById("favoriteheart");
const favoriteQuotes = [];

favoriteHeart.addEventListener("click", function () {
  const currentQuote = quote.innerText; // to look for the content of the quote
  const currentPerson = person.innerText; //and the author
  const favoriteQuote = { quote: currentQuote, person: currentPerson };
  favoriteQuotes.push(favoriteQuote); //favoriteQuotes.push(favoriteQuote) to add a new favorite quote to the favoriteQuotes array it modifies the array by appending an element to it.
  console.log("Quote added to favorites!");
});

let favoritesButton = document.querySelector("#favorites");
//this is used to clearn the text are when the button favourite is played  to displayed the liked quotes
favoritesButton.addEventListener("click", function () {
  quote.innerHTML = ""; // Clear previous quote
  person.innerHTML = ""; // Clear previous person

  //first of all we check if ther is any favs quotes//
  if (favoriteQuotes.length > 0) {
    // i created a loop for eache favorite quote //

    favoriteQuotes.forEach((favorite, index) => {
      const favoriteQuote = document.createElement("span"); //we create elemnt//
      favoriteQuote.classList.add("quote"); // with a class quote//
      favoriteQuote.innerText = favorite.quote; // and we write the quote //

      const favoritePerson = document.createElement("div"); // we create an element a div
      favoritePerson.classList.add("person"); // with a class person
      favoritePerson.innerText = favorite.person; //write the author

      const quoteContainer = document.createElement("div");
      quoteContainer.appendChild(favoriteQuote); //The favorite quote and person elements are appended to a container element called "quoteContainer" using the appendChild method.
      quoteContainer.appendChild(favoritePerson);

      quote.appendChild(quoteContainer);

      if (index !== favoriteQuotes.length - 1) {
        //if this is not the  last fav quote create break//
        const space = document.createElement("br");
        quote.appendChild(space);
      }
    });
  }
  //incase u didnt like any quote yet no favourite quotes line will be showed //
  else {
    const noFavoritesQuote = document.createElement("span");
    noFavoritesQuote.classList.add("quote");
    noFavoritesQuote.innerText = "No favorite quotes.";

    quote.appendChild(noFavoritesQuote);
  }
});
